### ISSUE TITLE
How to move Atom without titlebar?

### ISSUE THREAD

**Issue by codesign5** [saadq/bliss-ui#3]
I hide the title bar now I could I move the atom like using a different monitor?

**Comment by saadq** [comment]
Hey there, I'm not sure if there is an elegant solution to this problem. The way I fixed this is by enabling move/dragging in the entire editor, and then disable dragging in the parts it shouldn't be there (like the text editing part, etc). 

Try putting this in your custom stylesheet:

```less
// Hack to allow the Atom window to be draggable even without a title bar.
body:not(.fullscreen) > atom-workspace {
  // Make the whole editor draggable
  -webkit-app-region: drag;

  // Manually disable draggability where we don't want it.
  .atom-dock-resize-handle,
  .editor,
  .key-binding-resolver,
  .linter,
  .settings-view,
  .tab-bar,
  .tab-bar .tab,
  .tree-view .entry,
  .tree-view-resize-handle,
  .panel-divider,
  .panel-bottom,
  .status-bar,
  .linter-line,
  .xterm,
  .left,
  .right,
  .left .pane,
  .right .pane,
  .github-PaneView,
  .item-views,
  atom-pane-resize-handle,
  atom-pane-resize-handle.horizontal:before,
  atom-pane-resize-handle.vertical:before,
  linter-message .linter-message-item,
  linter-message .linter-message-link {
    -webkit-app-region: no-drag;
  }
}
```
